services:
  relay:
    container_name: rssnotes
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - ./app/.env
    volumes:
      - ".env:/app/.env"
      - "./app/db:/app/db"
      - "./app/seedrelays.json:/app/seedrelays.json"
      - "./app/users.json:/app/frens.json"
     
    ports:
      - "3334:3334"
    restart: unless-stopped
    #init: true